feat: add fssa keys

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -59,6 +59,19 @@ function auth() {
     printf '5\ny\n' | gpg --command-fd 0 --edit-key "$moser_gpg_key_id" trust quit
     echo "Moser GPG Key added."
   fi
+
+  fssa_gpg_key_id="$(pass-cli item view "pass://Moser Consulting/FSSA GPG Key/ID")"
+  if [ -z "$fssa_gpg_key_id" ]; then
+    echo "FSSA GPG Key ID not found in password store."
+    return 1
+  fi
+  if ! gpg --list-keys "$fssa_gpg_key_id" >/dev/null 2>&1; then
+    echo "FSSA GPG Key not found locally. Importing..."
+    pass-cli item view "pass://Moser Consulting/FSSA GPG Key/public_key" | gpg --import
+    pass-cli item view "pass://Moser Consulting/FSSA GPG Key/private_key" | gpg --import
+    printf '5\ny\n' | gpg --command-fd 0 --edit-key "$fssa_gpg_key_id" trust quit
+    echo "FSSA GPG Key added."
+  fi
   {{- end }}
 }
 function findpkg() {
