refactor: require homebrew

diff --git a/run_onchange_install-packages.sh.tmpl b/run_onchange_install-packages.sh.tmpl
--- a/run_onchange_install-packages.sh.tmpl
+++ b/run_onchange_install-packages.sh.tmpl
@@ -1,4 +1,9 @@
 #!/bin/bash
+if ! command -v brew &> /dev/null; then
+  echo "Homebrew not found. Install Homebrew first."
+  echo `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
+  exit 1
+fi
 
 if command -v apt-get &> /dev/null; then
   sudo apt-get update
@@ -17,10 +22,6 @@ if command -v pacman &> /dev/null; then
   else
     sudo pacman -S --needed --noconfirm {{ range .packages.base.system }}{{ . | quote }} {{ end }}{{ range .packages.linux.pacman }}{{ . | quote }} {{ end }}
   fi
-fi
-
-if ! command -v brew &> /dev/null; then
-  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
 
 if command -v brew &> /dev/null; then
